version: '2.0'
services:
  db:
    image: mysql
    container_name: template_spring_boot_db
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "spring_template"
    volumes:
      - ./src/main/resources/db/migration:/docker-entrypoint-initdb.d/:ro
    expose:
      - 3306
  web:
    image: spring-boot-template:latest
    container_name: template-spring-web
    depends_on:
      - db
    ports:
     - 8888:8081
    environment:
      DB_HOST: db
      DB_PORT: "3306"
      DB_MYSQL_USER: "mysql"
      DB_MYSQL_PASS: "mysql"
      STAGE: "prod"
      DB_ON_CREATE_DB: "spring_template"

